<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Login.xsl"?>

<!DOCTYPE document [
	<!ELEMENT document (seccionVisaHome,seccionBeneficios1,seccionBeneficios2,seccionServicios1,seccionServicios2,seccionServicios3,seccionServicios4,seccionVisaHomeNew)>
	<!ELEMENT seccionVisaHome (titulo,texto,link)>
	<!ATTLIST seccionVisaHome
	   id ID #REQUIRED
   >
	<!ELEMENT seccionBeneficios1 (titulo,texto,link)>
	<!ATTLIST seccionBeneficios1
	   id ID #REQUIRED
   >
	<!ELEMENT seccionBeneficios2 (titulo,texto,link)>
	<!ATTLIST seccionBeneficios2
	   id ID #REQUIRED
   >
	<!ELEMENT seccionServicios1 (titulo,texto,link)>
	<!ATTLIST seccionServicios1
	   id ID #REQUIRED
   >
	<!ELEMENT seccionServicios2 (titulo,texto,link)>
	<!ATTLIST seccionServicios2
	   id ID #REQUIRED
   >
	<!ELEMENT seccionServicios3 (titulo,texto,link)>
	<!ATTLIST seccionServicios3
	   id ID #REQUIRED
   >
	<!ELEMENT seccionServicios4 (titulo,texto,link, link2)>
	<!ATTLIST seccionServicios4
	   id ID #REQUIRED
   >
  <!ELEMENT seccionVisaHomeNew (titulo, texto, link)>
  <!ATTLIST seccionVisaHomeNew
     id ID #REQUIRED
  >

	<!ATTLIST document
	   id ID #REQUIRED
   >
   <!ELEMENT titulo (#PCDATA)>
   <!ATTLIST titulo
      id ID #REQUIRED
   >
   <!ELEMENT texto (#PCDATA)>
   <!ATTLIST texto
      id ID #REQUIRED
   >
   <!ELEMENT link (#PCDATA)>
   <!ATTLIST link
      id ID #REQUIRED
   >
   <!ELEMENT link2 (#PCDATA)>
   <!ATTLIST link2
      id ID #REQUIRED
   >
]>
<document id="document">
	<seccionVisaHome id="seccionVisaHome">
		<titulo id="tituloVisaHome">VisaHome</titulo>
		<texto id="textoVisaHome">Le permite obtener gran cantidad de informacion acerca del estado de cuenta de sus tarjetas Visa. El servicio es gratuito, funciona las 24 horas del dia y se actualiza en tiempo real. </texto>
		<link id="linkVisaHome">VisaHome</link>
	</seccionVisaHome>
	<seccionBeneficios1 id="seccionBeneficios1">
		<titulo id="tituloPromos1"></titulo>
		<texto id="textoPromos1"></texto>
		<link id="linkPromos1">http://www.visa.com.ar</link>
	</seccionBeneficios1>
	<seccionBeneficios2 id="seccionBeneficios2">
		<titulo id="tituloPromos2"></titulo>
		<texto id="textoPromos2"></texto>
		<link id="linkPromos2">http://www.visa.com.ar/Socios/Promociones/home.asp</link>
	</seccionBeneficios2>
	<seccionServicios1 id="seccionServicios1">
		<titulo id="tituloSeccionServicios1">Servicio de Pagos Visa</titulo>
		<texto id="textoSeccionServicios1">Adhiera al Débito Automático y pague sus facturas de servicios con sus tarjetas Visa.</texto>
		<link id="linkSeccionServicios1"> http://www.visa.com.ar/Socios/Servicios/ServicioDePagosVisa.htm</link>
	</seccionServicios1>
	<seccionServicios2 id="seccionServicios2">
		<titulo id="tituloSeccionServicios2">VisaPhone</titulo>
		<texto id="textoSeccionServicios2">El servicio exclusivo para hablar desde donde quiera y cuando quiera, utilizando su tarjeta Visa.</texto>
		<link id="linkSeccionServicios2"> http://www.visa.com.ar/Socios/Servicios/VisaPhone.htm</link>
	</seccionServicios2>
	<seccionServicios3 id="seccionServicios3">
		<titulo id="tituloSeccionServicios3">Veraz Equifax</titulo>
		<texto id="textoSeccionServicios3">Acceda a toda la información On-line sobre personas y empresas. Ingrese aquí y pague su informe con Visa.</texto>
		<link id="linkSeccionServicios3">http://www.veraz.com.ar/web/visasocios</link>
	</seccionServicios3>
	<seccionServicios4 id="seccionServicios4">
		<titulo id="tituloSeccionServicios4">Visa Regalo</titulo>
		<texto id="textoSeccionServicios4">Usted puede conocer el saldo disponible y los &#250;ltimos movimientos realizados con su tarjeta Visa Regalo.</texto>
		<link id="linkSeccionServicios4">http://www.visa.com.ar/Empresa/Productos/ProductoRegalo.htm</link>
		<link2 id="link">http://www.visa.com.ar/Empresa/Productos/popup_consulta.htm</link2>
	</seccionServicios4>
  <seccionVisaHomeNew id="seccionVisaHomeNew">
    <titulo id="tituloSeccionVisaHomeNew"></titulo>
    <texto id="textSeccionVisaHomeNew"></texto>
    <link id="linkSeccionVisaHomeNew">http://www.visa.com.ar/Socios/Servicios/seguridad.htm</link>
  </seccionVisaHomeNew>

</document>
